### ISSUE TITLE
Remove CSS style from the main Slider

### ISSUE THREAD

**Issue by williamtcastro** [MAOECOIN/site#6]
I propouse we remove the CSS effect from the main BG of the main page [EN]
Eu proponho que removamos o efeito do CSS aplicado ao BG principal na home page.

**Comment by rafaelvebercarvalho** [comment]
É para os Commits ser em inglês, aqui pode falar normal.

**Comment by williamtcastro** [comment]
ook, vlw pelos toques.

**Comment by williamtcastro** [comment]
Issue concertado no Slider Update
